'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CourseDrawer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _04_maps() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_04_maps", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property butAddNode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butAddNode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butDelCrs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butDelCrs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butDeleteNode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butDeleteNode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butFillNodes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butFillNodes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butInsertNode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butInsertNode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butMove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butNewCrs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butNewCrs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butRecalcDir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butRecalcDir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property butZoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("butZoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property magnify() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("magnify", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
